version: '3.8'

services:
  app:
    build: .
    container_name: proveedores-app
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
      APP_SECRET: docker_secret_123
      DATABASE_URL: "mysql://root:root@db:3306/proveedores_viajesPTi?serverVersion=8.0&charset=utf8mb4"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: proveedores-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proveedores_viajesPTi
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
